decay_channel: 'diphoton'

branching_ratio: 0.00227   # branching ratio for H -> aa

signal:
  path: 'data/VBF_diphoton.h5'
  cut_info: 'data/selection_results_VBF_quark_jet.npy'
  cross_section: 4278.0    # 4.278 * 1000, precomputed

background:
  path: 'data/GGF_diphoton.h5'
  cut_info: 'data/selection_results_GGF_quark_jet.npy'
  cross_section: 54670.0   # 54.67 * 1000, precomputed