decay_channel: 'zz4l'

branching_ratio: 0.000124  # branching ratio for H -> ZZ -> 4l

signal:
  path: 'data/VBF_zz4l.h5'
  cut_info: 'data/selection_results_VBF_ZZ_4l_quark_jet.npy'
  cross_section: 4278.0    # 4.278 * 1000, precomputed

background:
  path: 'data/GGF_zz4l.h5'
  cut_info: 'data/selection_results_GGF_ZZ_4l_quark_jet.npy'
  cross_section: 54670.0   # 54.67 * 1000, precomputed
