preprocessings: []

augmentations:
  functions: ['phi_uni']
  rotations: 15

Trainer:
  max_epochs: 200             # maximum number of epochs to train the model
  accelerator: 'gpu'          # 'cpu' or 'gpu'
  accumulate_grad_batches: 4  # number of batches to accumulate gradients over

LitDataModule:
  mode: 'jet_flavor'    # 'jet_flavor' or 'pure_random'
  
  batch_size: 128       # batch size for training
  train_size: 0.8       # fraction of training / (training + validation)
  num_train: 10000      # number of training samples for 'pure_random' mode
  num_valid: 1000       # number of validation samples for 'pure_random' mode
  num_test: 1000        # number of test samples for both 'jet_flavor' and 'pure_random' modes
